### ISSUE TITLE
Error rendering DOM element with declared Scope

### ISSUE THREAD

**Issue by GavinMcGraw** [zachlankton/DOM-Data-Mirror#1]
When using a declared scope with DOM element that has the same name as a different element under the dData scope, the items under the root with the declared scope render as hidden input elements.

```html
<div d-data scope="scope" name="app">
     <div d-data name="test">
          <span name="testElement1">Test Value 1</span>
     </div>
</div>
<div d-data name="app"> 
     <div name="test2">
          <span name="testElement2">Test Value 2</span>
     </div>
</div>
```
with script like
```javascript
scope.app = {
     test: [
          {testElement1: "Test Value 1.0"},
          {testElement1: "Test Value 1.1"},
          {testElement1: "Test Value 1.2"}
     ]
};
```

Test Element 1 will render as a hidden input fields

**Comment by zachlankton** [comment]
I've narrowed it down to the second app overwriting child templates of the first app on the body tag.  This happens during the setupChildTemplates Function... I need to figure out how to refactor the code to scope the templates.
